#for i in MAQUINARIAS TESORERIA REPUESTOS TALLER COMPRAS CONTABILIDAD GENERALES MENU CAJA COBRANZAS VEHICULOS COMISIONES
for i in `ls /FOBOS/DESARROLLO/PRODUCCION`
do
	echo $PWD
	sh comp_modulo.sh $i
done
