fglschema $1

#for i in LIBRERIAS TESORERIA REPUESTOS TALLER COMPRAS CONTABILIDAD GENERALES MENU CAJA COBRANZAS VEHICULOS COMISIONES
for i in `ls /FOBOS/DESARROLLO/PRODUCCION`
do
	cp $1.sch $i/fuentes/.
	cp $1.sch $i/forms/.
done
