IFXSERVER=$INFORMIXSERVER
HSTSERVER=$(hostname -s)
BASE_CENTRO=acero_gc
IFXSERVER_CENTRO=idsgye01

case $IFXSERVER in
"ACGYE01")	BASE_LOCAL=acero_gm;
		IFXSERVER_LOCAL=idsgye01
	;;
"ACUIO01")	BASE_LOCAL=acero_qm;
		IFXSERVER_LOCAL=idsuio01
	;;
"ACUIO02")	BASE_LOCAL=acero_qs;
		IFXSERVER_LOCAL=idsuio02
	;;
esac

